name: Monitor Page

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest

    env:
      NAME: Honda S800 Listings
      URL: https://carfromjapan.com/cheap-used-honda-s800-for-sale
      SELECTOR: '[data-testid="car-list-results"]'
      STATE_FILE: .github/monitor/car-list.hash

      NODE_VERSION: "22"
      OTP_VERSION: "27"
      ELIXIR_VERSION: "1.18"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Playwright
        run: |
          npm install playwright
          npx playwright install --with-deps chromium

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Run monitor
        id: monitor
        continue-on-error: true
        run: |
          set +e
          elixir watcher.exs
          echo "exit_code=$?" >> "$GITHUB_OUTPUT"

      - name: Debug state file
        run: |
          echo "Repository files:"
          ls -la
          echo
          echo ".github contents:"
          ls -la .github || true
          echo
          echo "Monitor state:"
          ls -la "$(dirname "$STATE_FILE")" || true

      - name: Commit updated state
        if: steps.monitor.outputs.exit_code != '1'
        run: |
          if [ -f "$STATE_FILE" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            git add "$STATE_FILE"

            git diff --cached --quiet || git commit -m "Update monitor state"
            git push
          else
            echo "No state file found. Nothing to commit."
          fi

      - name: Send email notification
        if: steps.monitor.outputs.exit_code == '2'
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.mail.me.com
          server_port: 587
          secure: false

          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          from: ${{ secrets.MAIL_USERNAME }}
          to: ${{ secrets.MAIL_TO }}

          subject: "🚗 ${{ env.NAME }} changed"

          body: |
            The monitored page has changed.

            Monitor:
            ${{ env.NAME }}

            URL:
            ${{ env.URL }}  
